# Generated by Django 3.1.2 on 2020-11-02 04:35

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.CharField(max_length=100)),
                ('Project_info', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='projects/images/default.jpg', force_format=None, keep_meta=True, quality=100, size=[500, 300], upload_to='projects/images/')),
                ('Project_URL', models.URLField(blank=True)),
            ],
        ),
    ]
